using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace CharacterMap.Generators.Readers;

[Generator]
public class ViewBaseViewModelReader : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 1. Find all partial class declarations
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax cds && cds.Modifiers.Any(m => m.ValueText == "partial"),
                transform: static (ctx, _) => ctx.Node as ClassDeclarationSyntax)
            .Where(static c => c is not null);

        // 2. Combine with compilation to perform semantic checks
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) =>
        {
            var (compilation, classes) = source;

            foreach (var classNode in classes)
            {
                var semanticModel = compilation.GetSemanticModel(classNode.SyntaxTree);
                if (semanticModel.GetDeclaredSymbol(classNode) is not INamedTypeSymbol classSymbol)
                    continue;

                // A. Check if the class inherits from ViewBase (directly or indirectly)
                bool inheritsFromViewBase = false;
                var baseType = classSymbol.BaseType;
                while (baseType != null)
                {
                    if (baseType.Name == "ViewBase")
                    {
                        inheritsFromViewBase = true;
                        break;
                    }
                    baseType = baseType.BaseType;
                }

                if (!inheritsFromViewBase)
                    continue;

                // B. Check if it already overrides GetViewModel()
                bool overridesGetViewModel = classNode.Members
                    .OfType<MethodDeclarationSyntax>()
                    .Any(m => m.Identifier.ValueText == "GetViewModel");

                if (overridesGetViewModel)
                    continue;

                // C. Check if it has a property named "ViewModel" in syntax or via [DependencyProperty("ViewModel")]
                bool hasViewModelProperty = classNode.Members
                    .OfType<PropertyDeclarationSyntax>()
                    .Any(p => p.Identifier.ValueText == "ViewModel");

                if (!hasViewModelProperty)
                {
                    foreach (var attributeList in classNode.AttributeLists)
                    {
                        foreach (var attribute in attributeList.Attributes)
                        {
                            var attrName = attribute.Name.ToString();
                            if (attrName.StartsWith("DependencyProperty"))
                            {
                                if (attribute.ArgumentList != null && attribute.ArgumentList.Arguments.Count > 0)
                                {
                                    var firstArg = attribute.ArgumentList.Arguments[0].ToString().Trim('"', ' ');
                                    if (firstArg == "ViewModel")
                                    {
                                        hasViewModelProperty = true;
                                        break;
                                    }
                                }
                            }
                        }
                        if (hasViewModelProperty)
                            break;
                    }
                }

                if (!hasViewModelProperty)
                    continue;

                // D. Generate the GetViewModel override
                string className = classNode.Identifier.ValueText;
                string ns = classNode.GetNamespace();

                // Retrieve usings from the compilation unit root
                var unit = classNode.SyntaxTree.GetRoot() as CompilationUnitSyntax;
                List<string> usings = unit?.Usings.Select(u => u.ToString()).ToList() ?? new();

                if (!usings.Any(u => u.Contains("CharacterMap.ViewModels")))
                    usings.Add("using CharacterMap.ViewModels;");

                string usingsStr = string.Join("\r\n", usings);

                string code = $@"// <auto-generated/>
{usingsStr}

namespace {ns};

partial class {className}
{{
    protected override ViewModelBase GetViewModel() => ViewModel;
}}";

                spc.AddSource($"{className}.g.vm.cs", SourceText.From(code, Encoding.UTF8));
            }
        });
    }
}
